read_file -type hdl $PROJECT_DIR/hdl/eda_compare.sv
read_file -type hdl $PROJECT_DIR/hdl/eda_controller.v
read_file -type hdl $PROJECT_DIR/hdl/eda_fifos.sv
read_file -type hdl $PROJECT_DIR/hdl/eda_img_ram.sv
read_file -type hdl $PROJECT_DIR/hdl/eda_iterated_ram.sv
read_file -type hdl $PROJECT_DIR/hdl/eda_max.sv
read_file -type hdl $PROJECT_DIR/hdl/eda_one_hot_to_bin.sv
read_file -type hdl $PROJECT_DIR/hdl/eda_output_ram.sv
read_file -type hdl $PROJECT_DIR/hdl/eda_regional_max.sv
read_file -type hdl $PROJECT_DIR/hdl/eda_strobe_ram.sv
read_file -type hdl $PROJECT_DIR/lib/sync_fifo/comparator.v
read_file -type hdl $PROJECT_DIR/lib/sync_fifo/read_control.v
read_file -type hdl $PROJECT_DIR/lib/sync_fifo/sync_fifo_mem.sv
read_file -type hdl $PROJECT_DIR/lib/sync_fifo/sync_fifo.v
read_file -type hdl $PROJECT_DIR/lib/sync_fifo/write_control.v
